/**
 * GENERATED FILE. Do not hand-edit.
 *
 * Regenerated by `npm run measure-extended-tier-bias` (scripts/measure-extended-tier-bias.ts).
 * CRED-03: the annualized volatility-drag understatement the extended tier's monthly-to-daily
 * interpolation hides, measured by inverting that exact transform over a known-good daily era.
 * Pinned by tests/validation/extended-tier-bias.test.ts, which fails the build if the committed
 * figure below no longer matches what the current bundle produces.
 */

/** Annualized fraction (e.g. 0.0553 means 5.53%/yr of understated volatility drag). */
export const EXTENDED_TIER_BIAS_ANNUALIZED_FRACTION = 0.0552913555510383

/** The symbol the measurement era's daily levels were drawn from. */
export const EXTENDED_TIER_BIAS_SYMBOL = "SPX"

/** The known-good daily era's first date (inclusive). */
export const EXTENDED_TIER_BIAS_ERA_FIRST_DATE = "2000-01-03"

/** The known-good daily era's last date (inclusive). */
export const EXTENDED_TIER_BIAS_ERA_LAST_DATE = "2012-12-31"

/** The leverage multiple both arms of the measurement ran at. */
export const EXTENDED_TIER_BIAS_LEVERAGE = 3

/** Copied verbatim from the bundle compiler's own seam-method wording template. */
export const EXTENDED_TIER_BIAS_INTERPOLATION_METHOD = "Linear interpolation of \"SPX/price-return\"'s monthly observations to daily, bounded by its own month-anchor dates."

/** ISO date this figure was last regenerated. Not itself a function of the bundle data, so the
 * pinning test does not assert this field against a live recomputation. */
export const EXTENDED_TIER_BIAS_MEASUREMENT_DATE = "2026-08-21"
