/**
 * GENERATED FILE. Do not hand-edit.
 *
 * Regenerated by `npm run compute-presets` (scripts/compute-presets.ts).
 * SHARE-06/D-18: every preset's headline outcome, computed once at build time against the
 * compiled bundle. Pinned by tests/app/presets.generated.test.ts, which fails the build if the
 * committed figures below no longer match what the current bundle produces.
 */

/** One computed outcome per entry in `PRESET_DEFINITIONS` (src/app/presets.ts), in the same
 * declaration order -- `id` values line up 1:1. */
export interface PresetOutcome {
  id: string
  finalValue: number
  totalContributed: number
  finalValueMultiple: number
  maxDrawdown: number
  ruined: boolean
  ruinDate: string | null
  barCount: number
  irr: number | null
  cagr: number | null
  firstDate: string
  lastDate: string
  truncatedForRateCoverage: boolean
}

export const PRESET_OUTCOMES: readonly PresetOutcome[] = [
  {
    id: "spx-3x-1929",
    finalValue: 16123873.39213996,
    totalContributed: 10000,
    finalValueMultiple: 1612.387339213996,
    maxDrawdown: 0.999088784744861,
    ruined: false,
    ruinDate: null,
    barCount: 24344,
    irr: 0.07913332017975327,
    cagr: 0.07913332018365837,
    firstDate: "1929-09-16",
    lastDate: "2026-08-14",
    truncatedForRateCoverage: true,
  },
  {
    id: "ndx-3x-2000-peak",
    finalValue: 3042.9101607864645,
    totalContributed: 10000,
    finalValueMultiple: 0.30429101607864645,
    maxDrawdown: 0.9998176107211568,
    ruined: false,
    ruinDate: null,
    barCount: 6636,
    irr: -0.04406663813828207,
    cagr: -0.04406663830743385,
    firstDate: "2000-03-27",
    lastDate: "2026-08-14",
    truncatedForRateCoverage: false,
  },
  {
    id: "spx-3x-high-rate-1979",
    finalValue: 14312.274032745,
    totalContributed: 10000,
    finalValueMultiple: 1.4312274032744998,
    maxDrawdown: 0.7405699725229982,
    ruined: false,
    ruinDate: null,
    barCount: 1008,
    irr: 0.09410985825335075,
    cagr: 0.09410985793781812,
    firstDate: "1979-01-02",
    lastDate: "1982-12-27",
    truncatedForRateCoverage: true,
  },
  {
    id: "tqqq-covid-crash",
    finalValue: 18239.87809511993,
    totalContributed: 10000,
    finalValueMultiple: 1.823987809511993,
    maxDrawdown: 0.699220743216521,
    ruined: false,
    ruinDate: null,
    barCount: 252,
    irr: 0.8270020081032912,
    cagr: 0.8270020078866755,
    firstDate: "2020-02-19",
    lastDate: "2021-02-17",
    truncatedForRateCoverage: true,
  },
  {
    id: "upro-covid-crash",
    finalValue: 10968.8072697904,
    totalContributed: 10000,
    finalValueMultiple: 1.0968807269790402,
    maxDrawdown: 0.7681682551111533,
    ruined: false,
    ruinDate: null,
    barCount: 252,
    irr: 0.09715941358774133,
    cagr: 0.09715941362117508,
    firstDate: "2020-02-19",
    lastDate: "2021-02-17",
    truncatedForRateCoverage: true,
  },
  {
    id: "spx-3x-2000-peak",
    finalValue: 60208.35621122923,
    totalContributed: 10000,
    finalValueMultiple: 6.020835621122923,
    maxDrawdown: 0.9820383276481306,
    ruined: false,
    ruinDate: null,
    barCount: 6637,
    irr: 0.07034371144620519,
    cagr: 0.07034371159990949,
    firstDate: "2000-03-24",
    lastDate: "2026-08-14",
    truncatedForRateCoverage: true,
  },
  {
    id: "spx-3x-dca-2000",
    finalValue: 4426773.292839138,
    totalContributed: 168000,
    finalValueMultiple: 26.34984102880439,
    maxDrawdown: 0.9373672692547919,
    ruined: false,
    ruinDate: null,
    barCount: 6637,
    irr: 0.1911188161850178,
    cagr: 0.2595035139822839,
    firstDate: "2000-03-24",
    lastDate: "2026-08-14",
    truncatedForRateCoverage: true,
  },
  {
    id: "spx-3x-entry-sensitivity",
    finalValue: 2825271.0040441947,
    totalContributed: 10000,
    finalValueMultiple: 282.52710040441946,
    maxDrawdown: 0.9820414033263001,
    ruined: false,
    ruinDate: null,
    barCount: 9726,
    irr: 0.1572972704876359,
    cagr: 0.1572972704024571,
    firstDate: "1988-01-05",
    lastDate: "2026-08-14",
    truncatedForRateCoverage: true,
  },
  {
    id: "spx-3x-2010s",
    finalValue: 162550.55975341232,
    totalContributed: 10000,
    finalValueMultiple: 16.255055975341232,
    maxDrawdown: 0.517339498374702,
    ruined: false,
    ruinDate: null,
    barCount: 2516,
    irr: 0.321798451643341,
    cagr: 0.3217984517826866,
    firstDate: "2010-01-04",
    lastDate: "2019-12-31",
    truncatedForRateCoverage: true,
  },
  {
    id: "upro-since-inception",
    finalValue: 1386402.3691272826,
    totalContributed: 10000,
    finalValueMultiple: 138.64023691272826,
    maxDrawdown: 0.768168255111153,
    ruined: false,
    ruinDate: null,
    barCount: 4311,
    irr: 0.3332342729424329,
    cagr: 0.333234272801173,
    firstDate: "2009-06-25",
    lastDate: "2026-08-14",
    truncatedForRateCoverage: true,
  },
]

/** The compiled bundle version every figure above was computed against. */
export const PRESET_OUTCOMES_BUNDLE_VERSION = "45a9f1ae6444"

/** ISO date this figure set was last regenerated. Not itself a function of the bundle data, so
 * the pinning test does not assert this field against a live recomputation. */
export const PRESET_OUTCOMES_MEASUREMENT_DATE = "2026-08-26"
